# Site settings
title: "Technical Professional Communication Blog"
description: > 
  Write a description of your website here.

author: Rachit Jaiswal
email: rachij@uw.edu
github_username: rachit-j

baseurl: "/tpc" # the subpath of your site, e.g. /blog
url: "https://rachit-j.github.io" # the base hostname & protocol for your site

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

