# Site settings
title: "Rachit's Writing Blog"
description: > 
  My ENGL 288 Technical Professional Communication Blog

author: Rachit Jaiswal
email: rachij@uw.edu
github_username: rachit-j

baseurl: "/tpc" # the subpath of your site, e.g. /blog
url: "https://rachit-j.github.io" # the base hostname & protocol for your site

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

